name: pos
description: Dart Implementation of the [ISO-8583] banking protocol for Point of Sale (POS) Devices.
version: 0.3.0
repository: https://github.com/xclud/dart_pos
homepage: https://pwa.ir

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_des: ^1.0.0
  convert: ^3.0.1

dev_dependencies:
  test: ^1.17.11
  lints: ^1.0.0
